export const COUNTRIES = [
    { label: 'Afganistán', value: 'Afganistán', code2: 'AF', code3: 'AFG' },
    { label: 'Albania', value: 'Albania', code2: 'AL', code3: 'ALB' },
    { label: 'Alemania', value: 'Alemania', code2: 'DE', code3: 'DEU' },
    { label: 'Andorra', value: 'Andorra', code2: 'AD', code3: 'AND' },
    { label: 'Angola', value: 'Angola', code2: 'AO', code3: 'AGO' },
    { label: 'Antigua y Barbuda', value: 'Antigua y Barbuda', code2: 'AG', code3: 'ATG' },
    { label: 'Arabia Saudita', value: 'Arabia Saudita', code2: 'SA', code3: 'SAU' },
    { label: 'Argelia', value: 'Argelia', code2: 'DZ', code3: 'DZA' },
    { label: 'Argentina', value: 'Argentina', code2: 'AR', code3: 'ARG' },
    { label: 'Armenia', value: 'Armenia', code2: 'AM', code3: 'ARM' },
    { label: 'Australia', value: 'Australia', code2: 'AU', code3: 'AUS' },
    { label: 'Austria', value: 'Austria', code2: 'AT', code3: 'AUT' },
    { label: 'Azerbaiyán', value: 'Azerbaiyán', code2: 'AZ', code3: 'AZE' },
    { label: 'Bahamas', value: 'Bahamas', code2: 'BS', code3: 'BHS' },
    { label: 'Bangladés', value: 'Bangladés', code2: 'BD', code3: 'BGD' },
    { label: 'Barbados', value: 'Barbados', code2: 'BB', code3: 'BRB' },
    { label: 'Baréin', value: 'Baréin', code2: 'BH', code3: 'BHR' },
    { label: 'Bélgica', value: 'Bélgica', code2: 'BE', code3: 'BEL' },
    { label: 'Belice', value: 'Belice', code2: 'BZ', code3: 'BLZ' },
    { label: 'Benín', value: 'Benín', code2: 'BJ', code3: 'BEN' },
    { label: 'Bielorrusia', value: 'Bielorrusia', code2: 'BY', code3: 'BLR' },
    { label: 'Birmania', value: 'Birmania', code2: 'MM', code3: 'MMR' },
    { label: 'Bolivia', value: 'Bolivia', code2: 'BO', code3: 'BOL' },
    { label: 'Bosnia y Herzegovina', value: 'Bosnia y Herzegovina', code2: 'BA', code3: 'BIH' },
    { label: 'Botsuana', value: 'Botsuana', code2: 'BW', code3: 'BWA' },
    { label: 'Brasil', value: 'Brasil', code2: 'BR', code3: 'BRA' },
    { label: 'Brunéi', value: 'Brunéi', code2: 'BN', code3: 'BRN' },
    { label: 'Bulgaria', value: 'Bulgaria', code2: 'BG', code3: 'BGR' },
    { label: 'Burkina Faso', value: 'Burkina Faso', code2: 'BF', code3: 'BFA' },
    { label: 'Burundi', value: 'Burundi', code2: 'BI', code3: 'BDI' },
    { label: 'Bután', value: 'Bután', code2: 'BT', code3: 'BTN' },
    { label: 'Cabo Verde', value: 'Cabo Verde', code2: 'CV', code3: 'CPV' },
    { label: 'Camboya', value: 'Camboya', code2: 'KH', code3: 'KHM' },
    { label: 'Camerún', value: 'Camerún', code2: 'CM', code3: 'CMR' },
    { label: 'Canadá', value: 'Canadá', code2: 'CA', code3: 'CAN' },
    { label: 'Catar', value: 'Catar', code2: 'QA', code3: 'QAT' },
    { label: 'Chad', value: 'Chad', code2: 'TD', code3: 'TCD' },
    { label: 'Chile', value: 'Chile', code2: 'CL', code3: 'CHL' },
    { label: 'China', value: 'China', code2: 'CN', code3: 'CHN' },
    { label: 'Chipre', value: 'Chipre', code2: 'CY', code3: 'CYP' },
    { label: 'Ciudad del Vaticano', value: 'Ciudad del Vaticano', code2: 'VA', code3: 'VAT' },
    { label: 'Colombia', value: 'Colombia', code2: 'CO', code3: 'COL' },
    { label: 'Comoras', value: 'Comoras', code2: 'KM', code3: 'COM' },
    { label: 'Corea del Norte', value: 'Corea del Norte', code2: 'KP', code3: 'PRK' },
    { label: 'Corea del Sur', value: 'Corea del Sur', code2: 'KR', code3: 'KOR' },
    { label: 'Costa de Marfil', value: 'Costa de Marfil', code2: 'CI', code3: 'CIV' },
    { label: 'Costa Rica', value: 'Costa Rica', code2: 'CR', code3: 'CRI' },
    { label: 'Croacia', value: 'Croacia', code2: 'HR', code3: 'HRV' },
    { label: 'Cuba', value: 'Cuba', code2: 'CU', code3: 'CUB' },
    { label: 'Dinamarca', value: 'Dinamarca', code2: 'DK', code3: 'DNK' },
    { label: 'Dominica', value: 'Dominica', code2: 'DM', code3: 'DMA' },
    { label: 'Ecuador', value: 'Ecuador', code2: 'EC', code3: 'ECU' },
    { label: 'Egipto', value: 'Egipto', code2: 'EG', code3: 'EGY' },
    { label: 'El Salvador', value: 'El Salvador', code2: 'SV', code3: 'SLV' },
    { label: 'Emiratos Árabes Unidos', value: 'Emiratos Árabes Unidos', code2: 'AE', code3: 'ARE' },
    { label: 'Eritrea', value: 'Eritrea', code2: 'ER', code3: 'ERI' },
    { label: 'Eslovaquia', value: 'Eslovaquia', code2: 'SK', code3: 'SVK' },
    { label: 'Eslovenia', value: 'Eslovenia', code2: 'SI', code3: 'SVN' },
    { label: 'España', value: 'España', code2: 'ES', code3: 'ESP' },
    { label: 'Estados Unidos', value: 'Estados Unidos', code2: 'US', code3: 'USA' },
    { label: 'Estonia', value: 'Estonia', code2: 'EE', code3: 'EST' },
    { label: 'Etiopía', value: 'Etiopía', code2: 'ET', code3: 'ETH' },
    { label: 'Filipinas', value: 'Filipinas', code2: 'PH', code3: 'PHL' },
    { label: 'Finlandia', value: 'Finlandia', code2: 'FI', code3: 'FIN' },
    { label: 'Fiyi', value: 'Fiyi', code2: 'FJ', code3: 'FJI' },
    { label: 'Francia', value: 'Francia', code2: 'FR', code3: 'FRA' },
    { label: 'Gabón', value: 'Gabón', code2: 'GA', code3: 'GAB' },
    { label: 'Gambia', value: 'Gambia', code2: 'GM', code3: 'GMB' },
    { label: 'Georgia', value: 'Georgia', code2: 'GE', code3: 'GEO' },
    { label: 'Ghana', value: 'Ghana', code2: 'GH', code3: 'GHA' },
    { label: 'Granada', value: 'Granada', code2: 'GD', code3: 'GRD' },
    { label: 'Grecia', value: 'Grecia', code2: 'GR', code3: 'GRC' },
    { label: 'Guatemala', value: 'Guatemala', code2: 'GT', code3: 'GTM' },
    { label: 'Guinea Ecuatorial', value: 'Guinea Ecuatorial', code2: 'GQ', code3: 'GNQ' },
    { label: 'Guinea', value: 'Guinea', code2: 'GN', code3: 'GIN' },
    { label: 'Guinea-Bisáu', value: 'Guinea-Bisáu', code2: 'GW', code3: 'GNB' },
    { label: 'Guyana', value: 'Guyana', code2: 'GY', code3: 'GUY' },
    { label: 'Haití', value: 'Haití', code2: 'HT', code3: 'HTI' },
    { label: 'Honduras', value: 'Honduras', code2: 'HN', code3: 'HND' },
    { label: 'Hungría', value: 'Hungría', code2: 'HU', code3: 'HUN' },
    { label: 'India', value: 'India', code2: 'IN', code3: 'IND' },
    { label: 'Indonesia', value: 'Indonesia', code2: 'ID', code3: 'IDN' },
    { label: 'Irak', value: 'Irak', code2: 'IQ', code3: 'IRQ' },
    { label: 'Irán', value: 'Irán', code2: 'IR', code3: 'IRN' },
    { label: 'Irlanda', value: 'Irlanda', code2: 'IE', code3: 'IRL' },
    { label: 'Islandia', value: 'Islandia', code2: 'IS', code3: 'ISL' },
    { label: 'Islas Marshall', value: 'Islas Marshall', code2: 'MH', code3: 'MHL' },
    { label: 'Islas Salomón', value: 'Islas Salomón', code2: 'SB', code3: 'SLB' },
    { label: 'Israel', value: 'Israel', code2: 'IL', code3: 'ISR' },
    { label: 'Italia', value: 'Italia', code2: 'IT', code3: 'ITA' },
    { label: 'Jamaica', value: 'Jamaica', code2: 'JM', code3: 'JAM' },
    { label: 'Japón', value: 'Japón', code2: 'JP', code3: 'JPN' },
    { label: 'Jordania', value: 'Jordania', code2: 'JO', code3: 'JOR' },
    { label: 'Kazajistán', value: 'Kazajistán', code2: 'KZ', code3: 'KAZ' },
    { label: 'Kenia', value: 'Kenia', code2: 'KE', code3: 'KEN' },
    { label: 'Kirguistán', value: 'Kirguistán', code2: 'KG', code3: 'KGZ' },
    { label: 'Kiribati', value: 'Kiribati', code2: 'KI', code3: 'KIR' },
    { label: 'Kuwait', value: 'Kuwait', code2: 'KW', code3: 'KWT' },
    { label: 'Laos', value: 'Laos', code2: 'LA', code3: 'LAO' },
    { label: 'Lesoto', value: 'Lesoto', code2: 'LS', code3: 'LSO' },
    { label: 'Letonia', value: 'Letonia', code2: 'LV', code3: 'LVA' },
    { label: 'Líbano', value: 'Líbano', code2: 'LB', code3: 'LBN' },
    { label: 'Liberia', value: 'Liberia', code2: 'LR', code3: 'LBR' },
    { label: 'Libia', value: 'Libia', code2: 'LY', code3: 'LBY' },
    { label: 'Liechtenstein', value: 'Liechtenstein', code2: 'LI', code3: 'LIE' },
    { label: 'Lituania', value: 'Lituania', code2: 'LT', code3: 'LTU' },
    { label: 'Luxemburgo', value: 'Luxemburgo', code2: 'LU', code3: 'LUX' },
    { label: 'Macedonia del Norte', value: 'Macedonia del Norte', code2: 'MK', code3: 'MKD' },
    { label: 'Madagascar', value: 'Madagascar', code2: 'MG', code3: 'MDG' },
    { label: 'Malasia', value: 'Malasia', code2: 'MY', code3: 'MYS' },
    { label: 'Malaui', value: 'Malaui', code2: 'MW', code3: 'MWI' },
    { label: 'Maldivas', value: 'Maldivas', code2: 'MV', code3: 'MDV' },
    { label: 'Malí', value: 'Malí', code2: 'ML', code3: 'MLI' },
    { label: 'Malta', value: 'Malta', code2: 'MT', code3: 'MLT' },
    { label: 'Marruecos', value: 'Marruecos', code2: 'MA', code3: 'MAR' },
    { label: 'Mauricio', value: 'Mauricio', code2: 'MU', code3: 'MUS' },
    { label: 'Mauritania', value: 'Mauritania', code2: 'MR', code3: 'MRT' },
    { label: 'México', value: 'México', code2: 'MX', code3: 'MEX' },
    { label: 'Micronesia', value: 'Micronesia', code2: 'FM', code3: 'FSM' },
    { label: 'Moldavia', value: 'Moldavia', code2: 'MD', code3: 'MDA' },
    { label: 'Mónaco', value: 'Mónaco', code2: 'MC', code3: 'MCO' },
    { label: 'Mongolia', value: 'Mongolia', code2: 'MN', code3: 'MNG' },
    { label: 'Montenegro', value: 'Montenegro', code2: 'ME', code3: 'MNE' },
    { label: 'Mozambique', value: 'Mozambique', code2: 'MZ', code3: 'MOZ' },
    { label: 'Namibia', value: 'Namibia', code2: 'NA', code3: 'NAM' },
    { label: 'Nauru', value: 'Nauru', code2: 'NR', code3: 'NRU' },
    { label: 'Nepal', value: 'Nepal', code2: 'NP', code3: 'NPL' },
    { label: 'Nicaragua', value: 'Nicaragua', code2: 'NI', code3: 'NIC' },
    { label: 'Níger', value: 'Níger', code2: 'NE', code3: 'NER' },
    { label: 'Nigeria', value: 'Nigeria', code2: 'NG', code3: 'NGA' },
    { label: 'Noruega', value: 'Noruega', code2: 'NO', code3: 'NOR' },
    { label: 'Nueva Zelanda', value: 'Nueva Zelanda', code2: 'NZ', code3: 'NZL' },
    { label: 'Omán', value: 'Omán', code2: 'OM', code3: 'OMN' },
    { label: 'Países Bajos', value: 'Países Bajos', code2: 'NL', code3: 'NLD' },
    { label: 'Pakistán', value: 'Pakistán', code2: 'PK', code3: 'PAK' },
    { label: 'Palaos', value: 'Palaos', code2: 'PW', code3: 'PLW' },
    { label: 'Palestina', value: 'Palestina', code2: 'PS', code3: 'PSE' },
    { label: 'Panamá', value: 'Panamá', code2: 'PA', code3: 'PAN' },
    { label: 'Papúa Nueva Guinea', value: 'Papúa Nueva Guinea', code2: 'PG', code3: 'PNG' },
    { label: 'Paraguay', value: 'Paraguay', code2: 'PY', code3: 'PRY' },
    { label: 'Perú', value: 'Perú', code2: 'PE', code3: 'PER' },
    { label: 'Polonia', value: 'Polonia', code2: 'PL', code3: 'POL' },
    { label: 'Portugal', value: 'Portugal', code2: 'PT', code3: 'PRT' },
    { label: 'Reino Unido', value: 'Reino Unido', code2: 'GB', code3: 'GBR' },
    { label: 'República Centroafricana', value: 'República Centroafricana', code2: 'CF', code3: 'CAF' },
    { label: 'República Checa', value: 'República Checa', code2: 'CZ', code3: 'CZE' },
    { label: 'República del Congo', value: 'República del Congo', code2: 'CG', code3: 'COG' },
    { label: 'República Democrática del Congo', value: 'República Democrática del Congo', code2: 'CD', code3: 'COD' },
    { label: 'República Dominicana', value: 'República Dominicana', code2: 'DO', code3: 'DOM' },
    { label: 'Ruanda', value: 'Ruanda', code2: 'RW', code3: 'RWA' },
    { label: 'Rumania', value: 'Rumania', code2: 'RO', code3: 'ROU' },
    { label: 'Rusia', value: 'Rusia', code2: 'RU', code3: 'RUS' },
    { label: 'Samoa', value: 'Samoa', code2: 'WS', code3: 'WSM' },
    { label: 'San Cristóbal y Nieves', value: 'San Cristóbal y Nieves', code2: 'KN', code3: 'KNA' },
    { label: 'San Marino', value: 'San Marino', code2: 'SM', code3: 'SMR' },
    { label: 'San Vicente y las Granadinas', value: 'San Vicente y las Granadinas', code2: 'VC', code3: 'VCT' },
    { label: 'Santa Lucía', value: 'Santa Lucía', code2: 'LC', code3: 'LCA' },
    { label: 'Santo Tomé y Príncipe', value: 'Santo Tomé y Príncipe', code2: 'ST', code3: 'STP' },
    { label: 'Senegal', value: 'Senegal', code2: 'SN', code3: 'SEN' },
    { label: 'Serbia', value: 'Serbia', code2: 'RS', code3: 'SRB' },
    { label: 'Seychelles', value: 'Seychelles', code2: 'SC', code3: 'SYC' },
    { label: 'Sierra Leona', value: 'Sierra Leona', code2: 'SL', code3: 'SLE' },
    { label: 'Singapur', value: 'Singapur', code2: 'SG', code3: 'SGP' },
    { label: 'Siria', value: 'Siria', code2: 'SY', code3: 'SYR' },
    { label: 'Somalia', value: 'Somalia', code2: 'SO', code3: 'SOM' },
    { label: 'Sri Lanka', value: 'Sri Lanka', code2: 'LK', code3: 'LKA' },
    { label: 'Suazilandia', value: 'Suazilandia', code2: 'SZ', code3: 'SWZ' },
    { label: 'Sudáfrica', value: 'Sudáfrica', code2: 'ZA', code3: 'ZAF' },
    { label: 'Sudán del Sur', value: 'Sudán del Sur', code2: 'SS', code3: 'SSD' },
    { label: 'Sudán', value: 'Sudán', code2: 'SD', code3: 'SDN' },
    { label: 'Suecia', value: 'Suecia', code2: 'SE', code3: 'SWE' },
    { label: 'Suiza', value: 'Suiza', code2: 'CH', code3: 'CHE' },
    { label: 'Surinam', value: 'Surinam', code2: 'SR', code3: 'SUR' },
    { label: 'Tailandia', value: 'Tailandia', code2: 'TH', code3: 'THA' },
    { label: 'Tanzania', value: 'Tanzania', code2: 'TZ', code3: 'TZA' },
    { label: 'Tayikistán', value: 'Tayikistán', code2: 'TJ', code3: 'TJK' },
    { label: 'Timor Oriental', value: 'Timor Oriental', code2: 'TL', code3: 'TLS' },
    { label: 'Togo', value: 'Togo', code2: 'TG', code3: 'TGO' },
    { label: 'Tonga', value: 'Tonga', code2: 'TO', code3: 'TON' },
    { label: 'Trinidad y Tobago', value: 'Trinidad y Tobago', code2: 'TT', code3: 'TTO' },
    { label: 'Túnez', value: 'Túnez', code2: 'TN', code3: 'TUN' },
    { label: 'Turkmenistán', value: 'Turkmenistán', code2: 'TM', code3: 'TKM' },
    { label: 'Turquía', value: 'Turquía', code2: 'TR', code3: 'TUR' },
    { label: 'Tuvalu', value: 'Tuvalu', code2: 'TV', code3: 'TUV' },
    { label: 'Ucrania', value: 'Ucrania', code2: 'UA', code3: 'UKR' },
    { label: 'Uganda', value: 'Uganda', code2: 'UG', code3: 'UGA' },
    { label: 'Uruguay', value: 'Uruguay', code2: 'UY', code3: 'URY' },
    { label: 'Uzbekistán', value: 'Uzbekistán', code2: 'UZ', code3: 'UZB' },
    { label: 'Vanuatu', value: 'Vanuatu', code2: 'VU', code3: 'VUT' },
    { label: 'Venezuela', value: 'Venezuela', code2: 'VE', code3: 'VEN' },
    { label: 'Vietnam', value: 'Vietnam', code2: 'VN', code3: 'VNM' },
    { label: 'Yemen', value: 'Yemen', code2: 'YE', code3: 'YEM' },
    { label: 'Yibuti', value: 'Yibuti', code2: 'DJ', code3: 'DJI' },
    { label: 'Zambia', value: 'Zambia', code2: 'ZM', code3: 'ZMB' },
    { label: 'Zimbabue', value: 'Zimbabue', code2: 'ZW', code3: 'ZWE' }
];

export const getCountryData = (name) => {
    return COUNTRIES.find(c => c.label.toLowerCase() === name.toLowerCase());
};
